### ISSUE TITLE
Article DOI

### ISSUE THREAD

**Issue by Sabdellaoui1805** [zzxjl1/RailwayTurnoutGuard#1]
Hello, can i have the DOI of the corresponding article ?
Thank you!

**Comment by zzxjl1** [comment]
I appreciate your eagerness to access the DOI. However, I'm still in the process of completing the paper. I will gladly share the DOI with you once it's online. Thank you for your understanding and patience.

**Comment by zzxjl1** [comment]
Hi there! We have finished the 1st round major revision of our manuscript. Stay tuned!

> Hello, can i have the DOI of the corresponding article ? Thank you!

**Comment by zzxjl1** [comment]
In case you're in a hurry, we are glad to upload a preprint version to the arxiv platform.

**Comment by Sabdellaoui1805** [comment]
Yes, I would appreciate it! Thank you!

**Comment by zzxjl1** [comment]
Our work titled `Real-time and Downtime-tolerant Fault Diagnosis for Railway Turnout Machines (RTMs) Empowered with Cloud-Edge Pipeline Parallelism` goes beyond just fault detection for turnout machines. It also focuses on the cloud-edge collaborative deployment of the model, which aligns with my primary research area. **You may not need to refer to the entire paper, especially since half of it deals with computer network-related content, but the sections related to the model are the most relevant.**

Please feel free to reach out if you have any questions or would like to exchange contact information for further discussion.

arxiv link: [https://arxiv.org/abs/2411.02086](https://arxiv.org/abs/2411.02086)
